import "./globals.css";
import "react-toastify/dist/ReactToastify.min.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Notification from "@components/Notification";
import AuthSession from "./components/AuthSession";
import Provider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Peanuts Closet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthSession>
      <html lang="en">
        <body className={inter.className}>
          <Provider>{children}</Provider>
          <Notification />
        </body>
      </html>
    </AuthSession>
  );
}
